In [1]:
import numpy
# create a one dimensional array
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
# reshape to a two dimensional array
n = n.reshape(3, 9)
n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [4]:
# reshape to 3 dimensional array
n = n.reshape(3, 3, 3)
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
# convert a python list to a numpy array
lst = [[20,20,45], [12,12,4]]
type(lst)

list

In [8]:
nparray = numpy.asarray(lst)
type(nparray)

numpy.ndarray

In [7]:
nparray

array([[20, 20, 45],
       [12, 12,  4]])

In [15]:
# image processing with cv2
import cv2
# load a 5 by 3 grayscale image from disk in grayscale - this would convert colour to gray representation if it was a colour image loaded
img = cv2.imread('smallgray.png', 0) 
type(img)


numpy.ndarray

In [16]:
print(img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [17]:
img2 = cv2.imread('smallgray.png', 1) # load as RGB
type(img2)

numpy.ndarray

In [18]:
print(img2) # note this is 3 dimensional since each pixel has a R value, G value and B value rather than just a grayscale value

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [19]:
# write an image from a numpy array
cv2.imwrite('new_smallgray.png', img2)

True

In [20]:
import os
os.listdir()

['Untitled4.ipynb',
 'numpy.ipynb',
 'geocoding_example.ipynb',
 'supermarkets.xlsx',
 'jupyter_json.ipynb',
 'supermarkets.json',
 '.ipynb_checkpoints',
 'supermarkets-commas.txt',
 'new_smallgray.png',
 'Untitled1.ipynb',
 '.git',
 'supermarkets.csv',
 'jupyter_excel.ipynb',
 'Untitled3.ipynb',
 'Untitled2.ipynb',
 'smallgray.png',
 'supermarkets-semi-colons.txt',
 'README.md',
 '.gitignore',
 'csv_notebook.ipynb',
 'Untitled.ipynb']

In [22]:
# slice the numpy arrays as you would lists - operand exclusive like lists
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
img[0:2, 2:4] # so 1st and 2nd row, 3rd and 4th column

array([[104, 121],
       [255, 255]], dtype=uint8)

In [28]:
# iterate over each row
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [29]:
# transpose rows and columns and iterate over each column
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [30]:
# iterate over each value
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [32]:
# horizontally stack two (or more) arrays together - just add img to itself, note - pass a tuple as the argument, hstack only takes one arg
# arrays have to have the same dimensions to be stacked
hstacked = numpy.hstack((img, img))
hstacked

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [33]:
# vertically stack arrrays
vstacked = numpy.vstack((img, img))
vstacked

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [34]:
# split an array - have to split to a whole number i.e. with 5 columns, can't split by 3 - below split by 5 so from 5 columns get 5 arrays
# hsplit and vsplit methods like above
# split gives you python list back, not an array
hsplitted = numpy.hsplit(img, 5)
hsplitted

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]